# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        font = QtGui.QFont()
        font.setFamily("黑体")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 70, 150, 100))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 240, 150, 100))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 410, 150, 100))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.num1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.num1.setGeometry(QtCore.QRect(370, 60, 300, 120))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.num1.setFont(font)
        self.num1.setSmallDecimalPoint(False)
        self.num1.setDigitCount(5)
        self.num1.setMode(QtWidgets.QLCDNumber.Dec)
        self.num1.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.num1.setProperty("value", 0.0)
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.num2.setGeometry(QtCore.QRect(370, 230, 300, 120))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.num2.setFont(font)
        self.num2.setSmallDecimalPoint(False)
        self.num2.setDigitCount(5)
        self.num2.setMode(QtWidgets.QLCDNumber.Dec)
        self.num2.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.num2.setProperty("value", 0.0)
        self.num2.setObjectName("num2")
        self.num3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.num3.setGeometry(QtCore.QRect(370, 400, 300, 120))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.num3.setFont(font)
        self.num3.setSmallDecimalPoint(False)
        self.num3.setDigitCount(5)
        self.num3.setMode(QtWidgets.QLCDNumber.Dec)
        self.num3.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.num3.setProperty("value", 0.0)
        self.num3.setObjectName("num3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 60, 200, 120))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(60)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 230, 200, 120))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(60)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(690, 400, 200, 120))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(70)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "薇盾监控面板"))
        self.label.setText(_translate("MainWindow", "土壤温度:"))
        self.label_2.setText(_translate("MainWindow", "空气温度:"))
        self.label_3.setText(_translate("MainWindow", "空气湿度："))
        self.label_4.setText(_translate("MainWindow", "℃"))
        self.label_5.setText(_translate("MainWindow", "℃"))
        self.label_6.setText(_translate("MainWindow", "%"))

